name: DipSA CICD Workshop
on:
  release: 
    types: [published]


jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:

      # Step 1 ==> Checkout
      - 
        name: Checkout the code from github repo
        uses: actions/checkout@v3

      # Step 2 ==> Docker login
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Step 3 ==> Docker build and push
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: zhaoziyouuuu/randnum:${{ github.ref_name }} 

      # Step 4 ==> Slack notification
      - 
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {             
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: Zhao Ziyou \n Matriculation: ${{ secrets.NUS_MAT }} \n Email: ${{ secrets.OWN_EMAIL }} \n Repo: ${{ github.repositoryUrl }} \n Image name: zhaoziyouuuu/randnum:${{ github.ref_name }} \n Image url: https://hub.docker.com/repository/docker/zhaoziyouuuu/randnum "
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK