name: Pipeline to docker and slack
on:
  push:
    types: [published]
    tag:
    - v1.*

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:

      # Step 1 ==> Checkout
      - 
        name: Checkout the code from github repo
        uses: actions/checkout@v3

      # Step 2 ==> Docker login
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Step 3 ==> Docker build and push
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: zhaoziyouuuu/randnum:v0.4 

      # Step 4 ==> Slack notification
      - 
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {             
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: Zhao Ziyou \n Matriculation: A0184806X \n Email: nicoziyou@163.com \n Repo: git@github.com:ziyouu/randnum.git \n Image name: zhaoziyouuuu/randnum:${{ github.ref_name }} \n Image url: https://hub.docker.com/repository/docker/zhaoziyouuuu/randnum "
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK